# Generated by Django 3.2.9 on 2021-11-29 13:01

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0050_iprange'),
        ('tenancy', '0002_tenant_ordering'),
        ('extras', '0062_clear_secrets_changelog'),
        ('dcim', '0133_port_colors'),
        ('apbr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apbr',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('number', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
            ],
            options={
                'verbose_name_plural': 'AS Numbers',
            },
        ),
        migrations.CreateModel(
            name='ApbrGroup',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ApbrProfile',
        ),
        migrations.AddField(
            model_name='apbr',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apbr.apbrgroup'),
        ),
        migrations.AddField(
            model_name='apbr',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.role'),
        ),
        migrations.AddField(
            model_name='apbr',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apbr_related', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='apbr',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='apbr',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='apbr',
            constraint=models.UniqueConstraint(fields=('number', 'tenant'), name='apbr_tenant'),
        ),
        migrations.AddConstraint(
            model_name='apbr',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant', None)), fields=('number',), name='apbr'),
        ),
    ]
