# Generated by Django 3.2.9 on 2021-11-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apbr', '0002_auto_20211129_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apbr',
            options={'verbose_name_plural': 'APBR Profiles'},
        ),
    ]
