# Generated by Django 3.2.9 on 2021-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apbr', '0003_alter_apbr_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apbr',
            name='match',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apbr',
            name='then',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
